backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: rawsta/rawblog # Repo for pushing new commits. Make sure to replace with your repo!

locale: 'de'

media_folder: static/assets
public_folder: assets

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: blog
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Titel", name: "title", widget: "string", tagname: 'h1' }
      - { label: "Datum", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "false" }
      - { label: "Coverbild", name: "cover", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Kategorie", name: "category", widget: "string" }
      - { label: "HashTags", name: "tags", widget: "list" }
      - { editorComponents: ['youtube'], label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
